#ifndef LOVE_GRAPHICS_C_PIXELFORMAT_H
#define LOVE_GRAPHICS_C_PIXELFORMAT_H

#include "common/config.h"
#include "common/c_wrap.h"
#include "modules/love_c/types.h"

LOVE_C_EXTERN_C_BEGIN


typedef enum LoveC_Graphics_PixelFormat
  {
    PIXELFORMAT_UNKNOWN,

	// these are converted to an actual format by love
	PIXELFORMAT_NORMAL,
	PIXELFORMAT_HDR,

	// "regular" formats
	PIXELFORMAT_R8,
	PIXELFORMAT_RG8,
	PIXELFORMAT_RGBA8,
	PIXELFORMAT_sRGBA8,
	PIXELFORMAT_R16,
	PIXELFORMAT_RG16,
	PIXELFORMAT_RGBA16,
	PIXELFORMAT_R16F,
	PIXELFORMAT_RG16F,
	PIXELFORMAT_RGBA16F,
	PIXELFORMAT_R32F,
	PIXELFORMAT_RG32F,
	PIXELFORMAT_RGBA32F,

	PIXELFORMAT_LA8, // Same as RG8, but accessed as (L, L, L, A)

	// packed formats
	PIXELFORMAT_RGBA4,    // LSB->MSB: [a, b, g, r]
	PIXELFORMAT_RGB5A1,   // LSB->MSB: [a, b, g, r]
	PIXELFORMAT_RGB565,   // LSB->MSB: [b, g, r]
	PIXELFORMAT_RGB10A2,  // LSB->MSB: [r, g, b, a]
	PIXELFORMAT_RG11B10F, // LSB->MSB: [r, g, b]

	// depth/stencil formats
	PIXELFORMAT_STENCIL8,
	PIXELFORMAT_DEPTH16,
	PIXELFORMAT_DEPTH24,
	PIXELFORMAT_DEPTH32F,
	PIXELFORMAT_DEPTH24_STENCIL8,
	PIXELFORMAT_DEPTH32F_STENCIL8,

	// compressed formats
	PIXELFORMAT_DXT1,
	PIXELFORMAT_DXT3,
	PIXELFORMAT_DXT5,
	PIXELFORMAT_BC4,
	PIXELFORMAT_BC4s,
	PIXELFORMAT_BC5,
	PIXELFORMAT_BC5s,
	PIXELFORMAT_BC6H,
	PIXELFORMAT_BC6Hs,
	PIXELFORMAT_BC7,
	PIXELFORMAT_PVR1_RGB2,
	PIXELFORMAT_PVR1_RGB4,
	PIXELFORMAT_PVR1_RGBA2,
	PIXELFORMAT_PVR1_RGBA4,
	PIXELFORMAT_ETC1,
	PIXELFORMAT_ETC2_RGB,
	PIXELFORMAT_ETC2_RGBA,
	PIXELFORMAT_ETC2_RGBA1,
	PIXELFORMAT_EAC_R,
	PIXELFORMAT_EAC_Rs,
	PIXELFORMAT_EAC_RG,
	PIXELFORMAT_EAC_RGs,
	PIXELFORMAT_ASTC_4x4,
	PIXELFORMAT_ASTC_5x4,
	PIXELFORMAT_ASTC_5x5,
	PIXELFORMAT_ASTC_6x5,
	PIXELFORMAT_ASTC_6x6,
	PIXELFORMAT_ASTC_8x5,
	PIXELFORMAT_ASTC_8x6,
	PIXELFORMAT_ASTC_8x8,
	PIXELFORMAT_ASTC_10x5,
	PIXELFORMAT_ASTC_10x6,
	PIXELFORMAT_ASTC_10x8,
	PIXELFORMAT_ASTC_10x10,
	PIXELFORMAT_ASTC_12x10,
	PIXELFORMAT_ASTC_12x12,

	PIXELFORMAT_MAX_ENUM
  } LoveC_Graphics_PixelFormat;


LOVE_C_EXTERN_C_END

#endif // LOVE_GRAPHICS_C_PIXELFORMAT_H
